# 分类 [/api/genres]
## 获取分类枚举列表 [GET]
+ Response 200 (application/json)
        {
          "status": 0,
          "message": "ok",
          "data": [
            {
              "id": "5c1d07fb147b934a3d26333d",
              "name": "剧情"
            },
            {
              "id": "5c1d07fb147b934a3d26333e",
              "name": "动作"
            },
            {
              "id": "5c1d07fb147b934a3d26333f",
              "name": "犯罪"
            },
            {
              "id": "5c1d0816147b934a3d263340",
              "name": "家庭"
            },
            {
              "id": "5c1d0851147b934a3d263341",
              "name": "爱情"
            },
            {
              "id": "5c1d0851147b934a3d263342",
              "name": "动画"
            },
            {
              "id": "5c1d0865147b934a3d263343",
              "name": "喜剧"
            },
            {
              "id": "5c1d08a9147b934a3d263344",
              "name": "悬疑"
            },
            {
              "id": "5c1d08e7147b934a3d263345",
              "name": "传记"
            },
            {
              "id": "5c1d08e7147b934a3d263346",
              "name": "运动"
            },
            {
              "id": "5c1d08fd147b934a3d263347",
              "name": "科幻"
            },
            {
              "id": "5c1d08fd147b934a3d263348",
              "name": "冒险"
            },
            {
              "id": "5c1d0938147b934a3d263349",
              "name": "奇幻"
            },
            {
              "id": "5c1d0967147b934a3d26334a",
              "name": "历史"
            },
            {
              "id": "5c1d0967147b934a3d26334b",
              "name": "战争"
            },
            {
              "id": "5c1d0a35147b934a3d26334c",
              "name": "同性"
            },
            {
              "id": "5c1d0a8f147b934a3d26334d",
              "name": "惊悚"
            },
            {
              "id": "5c1d0ba5147b934a3d26334e",
              "name": "儿童"
            }
          ]
        }


# 电影 [/api/movie]
## 获取所有电影 [GET]
+ Response 200 (application/json)
        {
          "status": 0,
          "message": "ok",
          "data": [
            {
              "meta": {
                "updateTime": "2018-12-22T13:38:36.432Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d0865147b934a3d263343",
                "5c1d0851147b934a3d263342",
                "5c1d0816147b934a3d263340"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d263333",
              "title": "帕丁顿熊2",
              "rate": 8.1,
              "doubanId": "26340419",
              "__v": 1,
              "description": "露西婶婶（伊梅尔达·斯汤顿 Imelda Staunton 配音）的生日即将到来，帕丁顿（本·威士肖 Ben Whishaw 配音）决定送婶婶一份会让她终生难忘的礼物。最终，帕丁顿选中了一本立体绘本，然而这绘本是世间仅此一份的珍贵宝物，为了存钱购买绘本，帕丁顿决定开始工作，在遭遇了一连串的失败后，帕丁顿终于找到了适合他的工作——清洁玻璃窗。\n就在帕丁顿的存款即将达标之际，绘本竟然被一名神出鬼没的小偷给偷走了，同时出现在案发现场的帕丁顿被当做嫌疑犯捉拿归案，并最终被关进了监狱。在监狱里，帕丁顿凭借着自己的爱与勇气改变了墙内死气沉沉的氛围，监狱外，布朗一家人亦从来没有放弃过替帕丁顿洗清冤屈的机会。©豆瓣",
              "posterURL": "https://img1.doubanio.com/view/photo/l_ratio_poster/public/p2506466229.jpg",
              "posterURLKey": "lDUrcgq20xf7qw0KskjNE.jpeg",
              "rawTitle": "Paddington 2",
              "videoCoverURL": "https://img1.doubanio.com/img/trailer/medium/2507053509.jpg?",
              "videoCoverURLKey": "4bSKIsmRcKb5JFunNFqX1.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222138/289c545c9a42a4be363a06b2d474dc82/view/movie/M/302240803.mp4",
              "videoURLKey": "dfoZUpGrKOkF9fdBMEALj.mp4",
              "year": 2017
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:38:56.603Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d07fb147b934a3d26333e",
                "5c1d07fb147b934a3d26333f"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d263334",
              "title": "速度与激情5",
              "rate": 8.4,
              "doubanId": "4286017",
              "__v": 1,
              "description": "蛰伏2年之后，多米尼克（范•迪塞尔 Vin Diesel饰）与布莱恩（保罗•沃克 Paul Walker 饰）再度联手把火车中的神秘豪车盗走，遭到了警察和黑帮分子的火线追杀。布莱恩和米亚（乔丹娜•布鲁斯特 Jordana Brewster 饰）到里约寻找援兵，并与多米会和。为了寻找多米等人的下落，FBI王牌探员卢克（“岩石”道恩•强森 Dwayne Johnson饰）挺身而出，组成精英部队，追查来到里约。他雇佣了丧夫的美丽女警艾莲娜（埃尔莎•帕塔奇 Elsa Pataky 饰），一同寻找多米。与此同时，里约的地头蛇也对这些不速之客开火。三股势力开始相互缠斗。\n期间，因米亚怀孕，布莱恩决定陪她一起逃亡，所以多米只得依靠昔日老友探寻新车的秘密。在罗曼、韩等人的帮助下，多米终于找到了这辆车的秘密——芯片，并由此揭开了其中隐藏的一个不可告人的计划……©豆瓣",
              "posterURL": "https://img3.doubanio.com/view/photo/l_ratio_poster/public/p898634801.jpg",
              "posterURLKey": "IFJfmkz7oXugQmXTabOss.jpeg",
              "rawTitle": "Fast Five",
              "videoCoverURL": "https://img3.doubanio.com/img/trailer/medium/1220588962.jpg?",
              "videoCoverURLKey": "HUqmGmK7SnGEXLPqQFyLk.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222138/5440a163e08b328d99c99d5823121d62/view/movie/M/301000952-1.mp4",
              "videoURLKey": "8NQJx4KbjMm9dnqKr_81Z.mp4",
              "year": 2011
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:39:17.801Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d07fb147b934a3d26333d",
                "5c1d0a8f147b934a3d26334d"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d263335",
              "title": "黑天鹅",
              "rate": 8.5,
              "doubanId": "1978709",
              "__v": 1,
              "description": "纽约剧团要重排《天鹅湖》，因前领舞Beth（薇诺娜•赖德 Winona Ryder 饰）离去，总监Thomas（文森特•卡索尔 Vincent Cassel. 饰）决定海选新领舞，且要求领舞要分饰黑天鹅与白天鹅。Nina（娜塔莉•波特曼Natalie Portman 饰）自幼练习芭蕾舞，在母亲的细心关照下，技艺出众。这次，她希望可以脱颖而出。然而，在竞争中，她发现心机颇重的Lily（米拉•库妮丝 Mila Kunis 饰）是自己的强劲对手。在选拔中，她的白天鹅表演的无可挑剔，但是黑天鹅不及Lily。她感到身心俱疲，回家还发现了背部的红斑与脚伤。她一个人找到总监，希望争取一下。总监趁机亲吻她，却被她强硬拒绝。结果，总监居然选了她。队友怀疑她靠色相上位。在酒会上，Beth甚至当众发泄。这种压力外加伤病，一直影响着她的发挥。总监启发她要释放激情，表现出黑天鹅的诱惑。在强大的心理暗示中，她似乎也滑向了黑天鹅的角色……©豆瓣",
              "posterURL": "https://img3.doubanio.com/view/photo/l_ratio_poster/public/p719282906.jpg",
              "posterURLKey": "8DCriAXlfKY6DeaNu0nmr.jpeg",
              "rawTitle": "Black Swan",
              "videoCoverURL": "https://img3.doubanio.com/img/trailer/medium/2024330701.jpg?",
              "videoCoverURLKey": "iMXCKm_9ElyqA-ZHT39bk.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222139/94c647463115741dae0fc2bd96c1e4f6/view/movie/M/301370640.mp4",
              "videoURLKey": "CO8WIWS2O1ygcFFW36zrS.mp4",
              "year": 2010
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:39:34.674Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d07fb147b934a3d26333e",
                "5c1d0a8f147b934a3d26334d",
                "5c1d08fd147b934a3d263348"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d263336",
              "title": "碟中谍4",
              "rate": 8.3,
              "doubanId": "3068206",
              "__v": 1,
              "description": "特工汉纳威（乔什·哈洛威 Josh Holloway 饰）执行任务时遇害，核机密文件被女杀手莫伦（蕾雅·赛杜 Léa Seydoux 饰）截获。为了找回文件，特工班吉（西蒙·佩吉 Simon Pegg 饰）和特工简（宝拉·巴顿 Paula Patton 饰）从俄罗斯监狱救出了伊桑·亨特（汤姆·克鲁斯 Tom Cruise 饰）。他们接受的幽灵协议任务便是从克林姆林宫盗取核军事密码。然而，当他们接近目标时，却发现被恐怖分子亨德里克斯（迈克尔·恩奎斯特 Michael Nyqvist 饰）捷足先登，抢走了核军事密码。在爆炸中，亨特受困医院，遭俄特工的追捕，幸好他身手矫捷，才化险为夷。不过，亨特的上司也在混乱中丧生，只剩下其助手布兰德（杰瑞米·雷纳 Jeremy Renner 饰）与亨特死里逃生，加上班吉和简，逼上绝境的四人开始了最后一搏，从迪拜到印度，他们出生入死，与恐怖分子斗智斗勇……©豆瓣",
              "posterURL": "https://img1.doubanio.com/view/photo/l_ratio_poster/public/p1382432968.jpg",
              "posterURLKey": "c4v5uMa10htpFAjs0ysBP.jpeg",
              "rawTitle": "Mission: Impossible - Ghost Protocol",
              "videoCoverURL": "https://img3.doubanio.com/img/trailer/medium/1381110770.jpg?",
              "videoCoverURLKey": "hyIIMcezruAwnYS5G9ius.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222139/fbd1152ac0f56b8908df2d3c55ce2466/view/movie/M/301060445.mp4",
              "videoURLKey": "2L9EOMeJ4xn3WXI2tIQI5.mp4",
              "year": 2011
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:39:53.846Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d08fd147b934a3d263347",
                "5c1d08a9147b934a3d263344",
                "5c1d0a8f147b934a3d26334d"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d263338",
              "title": "源代码",
              "rate": 8.4,
              "doubanId": "3075287",
              "__v": 1,
              "description": "在阿富汗执行任务的美国空军飞行员科特史蒂文斯上尉（杰克·吉伦哈尔 Jake Gyllenhaal 饰）突然惊醒，发现自己在一辆高速行驶的列车上，而他的身边坐着一个素不相识的女子克里斯蒂安（米歇尔·莫娜汉 Michelle Monaghan 饰）正在与自己讲话。科尔不知自己为什么会在这辆车上，而且他发现自己居然是以另一个人的身份存在，正当他迷惑不解的时候，列车上忽然发生爆炸……\n科特又一次惊醒，发现自己身处一个密闭的太空仓里，有一位女军官古德温（维拉·法米加 Vera Farmiga 饰）正在通过视频和自己对话，并要求自己报告列车上发生的事情。一头雾水的科特还没搞明白是怎么回事时，他又一次被送上那辆列车。这次之后，科特终于明白自己在执行一件任务，负责调察芝加哥火车爆炸案找到恐怖份子并查出他的下一个目标。科特被一次又一次的送上那辆高速列车，每次只有八分钟的时间调察，调察过程中，科特发现自己已在一周前去世，原来他正在参与是一项“脑波原代码”的秘密任务，这项任务通过已经死亡的科特尚未完全死亡的脑细胞影像来还原事件，调查事情的真相。最终，科特顺利完成了任务，但是他却决定再一次返回列车，拯救列车上那些无辜的生命……©豆瓣",
              "posterURL": "https://img3.doubanio.com/view/photo/l_ratio_poster/public/p988260245.jpg",
              "posterURLKey": "b63PVEABZOrHyy86Nsz_b.jpeg",
              "rawTitle": "Source Code",
              "videoCoverURL": "https://img3.doubanio.com/img/trailer/medium/1346111093.jpg?",
              "videoCoverURLKey": "EPv189aCozyHu0UI4VbM-.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222139/e3f5e473fec8bfe2b35c5998f34dd2f6/view/movie/M/301040704.mp4",
              "videoURLKey": "fVDOIHlwBLEOs0RVS3YsS.mp4",
              "year": 2011
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:40:15.146Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d0851147b934a3d263342",
                "5c1d0938147b934a3d263349",
                "5c1d08fd147b934a3d263348"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d263337",
              "title": "借东西的小人阿莉埃蒂",
              "rate": 8.7,
              "doubanId": "4202302",
              "__v": 1,
              "description": "虽然患有心脏方面的疾病，但是少年翔（神木隆之介 配音）的父母依然对他疏于呵护。为了准备即将到来的手术，翔来到了位于偏远乡间的姨婆（竹下景子 配音）家静养。姨婆家位于一片幽静的丛林中，这是一幢有着上百年历史的欧式别墅。这里除了生活着姨婆和女佣阿春（树木希林 配音）外，还有一个奇特的三口之家，“借东西一族”——小人阿莉埃蒂（志田未来 配音）和她的爸爸（三浦友和 配音）妈妈（大竹忍 配音），他们生活在别墅的地板下，只有几公分高，过着不为人类察觉的生活。遇到所需的日常用品时，便会在夜深人静之时偷偷潜入厨房借出来。翔无疑中瞥见阿莉埃蒂的身影，他有心接近这些传说中的小人，却不知不觉打扰了他们的生活……\n本片根据英国作家玛丽·诺顿的原著《借东西的小人》改编，并荣获2011年日本电影学院奖最佳动画片奖。©豆瓣",
              "posterURL": "https://img3.doubanio.com/view/photo/l_ratio_poster/public/p617533616.jpg",
              "posterURLKey": "uwWTKjf4BnIa5-y48f6rd.jpeg",
              "rawTitle": "借りぐらしのアリエッティ",
              "videoCoverURL": "https://img3.doubanio.com/img/trailer/medium/1273375063.jpg?",
              "videoCoverURLKey": "ubxG7E1h6SVbhhColmJ26.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222140/72e31274aed04040f522c9672dd5f6e0/view/movie/M/301020403-1.mp4",
              "videoURLKey": "nNgyLdTMfJJLeSCfAVlsx.mp4",
              "year": 2010
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:40:36.140Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d07fb147b934a3d26333d",
                "5c1d07fb147b934a3d26333f",
                "5c1d08a9147b934a3d263344"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d263339",
              "title": "心迷宫",
              "rate": 8.7,
              "doubanId": "25917973",
              "__v": 1,
              "description": "一个想要挣脱父权控制的青年，在一次争执中失手杀死了同村的痞子，被迫逃亡。他没有想过会用这样的方式逃离安逸的生活，离开之际却惊人的发现宿命早已将他和专制的父亲紧紧连接在一起，走或留他都将失去一切。\n一个饱受家庭暴力摧残的留守女人，在曾经恋人的怀抱里找到了慰藉。黑暗里绝望的女人与情夫密谋杀夫，可当莽夫的死讯真的传来时，情夫却避而不见矢口否认一切。当女人又一次陷入绝望，另一个男人出现在她的生活里，他给女人带来的不仅仅是关心……\n一个行为正直严格自律的老村长，精心设计着自己退休后的晚年生活。一生忠诚于信仰的他，却在本性面前轻易地低下了头；一个污点掉落在命运蓝图上，他竭力去擦掉污迹，却剥开了一个黑洞，深陷其中。",
              "posterURL": "https://img3.doubanio.com/view/photo/l_ratio_poster/public/p2275298525.jpg",
              "posterURLKey": "hmry3hji6Xz4Gh6vys_9K.jpeg",
              "rawTitle": "心迷宫",
              "videoCoverURL": "https://img1.doubanio.com/img/trailer/medium/2274412287.jpg?",
              "videoCoverURLKey": "-Puv66YjW0qXwZFwqLF5V.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222140/5272fcd10b745e42f397972dfa0c9426/view/movie/M/301850017.mp4",
              "videoURLKey": "2Equ06ldH3wTtXPgfjmud.mp4",
              "year": 2014
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:40:54.875Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d0851147b934a3d263341",
                "5c1d0851147b934a3d263342"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d26333b",
              "title": "言叶之庭",
              "rate": 8.2,
              "doubanId": "20470074",
              "__v": 1,
              "description": "年方15岁的高中生秋月孝雄（入野自由 配音），专心学业的过程中不得不为了生计打工赚钱。母亲离家出走，他与哥哥过着看不到前方的生活。入梅之日，孝雄逃课来到日本庭园。在一座安静的小亭子里，27岁的职场女性雪野百香里（花泽香菜 配音）边吃巧克力边饮啤酒的样子引起了孝雄的注意。似曾相识的二人，仿佛约定好了一般，每到落雨之日便从世俗的烦恼中逃脱出来，相会于这座钢筋铁骨都市丛林中宛若世外桃源的幽静角落。在梅雨季节的日子里，他们的心渐渐向彼此靠拢。志愿成为手工鞋匠的秋月，决心以雪野为模特做一双鞋。\n雨过天晴，艳阳高照，庭园中久久不见秋月和雪野的身影，相会无期亦有期……©豆瓣",
              "posterURL": "https://img3.doubanio.com/view/photo/l_ratio_poster/public/p1958733032.jpg",
              "posterURLKey": "DRJiGnMJMOJm-44TCmmpk.jpeg",
              "rawTitle": "言の葉の庭",
              "videoCoverURL": "https://img3.doubanio.com/img/trailer/medium/1991168762.jpg?",
              "videoCoverURLKey": "bep5eo_5c_O3XQ7nRXENI.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222140/23ca17ba2e111028b7f954ca06b132b8/view/movie/M/301350747.mp4",
              "videoURLKey": "yrMFku3J5ML0VcHl2M3nq.mp4",
              "year": 2013
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:41:18.634Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d07fb147b934a3d26333d",
                "5c1d0816147b934a3d263340"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d26333c",
              "title": "罗马",
              "rate": 8.2,
              "doubanId": "1950330",
              "__v": 1,
              "description": "故事发生在墨西哥城的一个中产阶级社区“罗马”，讲述年轻女佣克里奥（雅利扎·阿巴里西奥饰）在雇主索菲亚（玛丽娜·德·塔维拉饰）家中工作，该家中索菲亚的丈夫长期在外，由女佣克里奥照顾索菲的四个孩子。突如其来的两个意外，同时砸中了女佣克里奥和雇主索菲亚，两人究竟该如何面对苦涩茫然的生活？四位孩子似乎是希望所在。 这是以导演阿方索·卡隆的儿时记忆铸成的影片，而卡隆其实就是片中某一位小孩。",
              "posterURL": "https://img3.doubanio.com/view/photo/l_ratio_poster/public/p2537733205.jpg",
              "posterURLKey": "xuckXNMye9CiQ69WnH3Zk.jpeg",
              "rawTitle": "Roma",
              "videoCoverURL": "https://img3.doubanio.com/img/trailer/medium/2541866642.jpg?1544171214",
              "videoCoverURLKey": "a7xcEc0rGzBN7AcCKj9DQ.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222141/f5b6ff53719d8e1f9c247124409a45d6/view/movie/M/402400326.mp4",
              "videoURLKey": "ucPiuCmqLY1tF0Kp5HgvZ.mp4",
              "year": 2018
            }, {
              "meta": {
                "updateTime": "2018-12-22T13:41:37.997Z",
                "createTime": "2018-12-21T15:34:17.161Z"
              },
              "genres": [
                "5c1d07fb147b934a3d26333d",
                "5c1d08e7147b934a3d263345"
              ],
              "hasDetail": true,
              "_id": "5c1d07f9147b934a3d26333a",
              "title": "萨利机长",
              "rate": 8.3,
              "doubanId": "26416603",
              "__v": 1,
              "description": "影片根据真实事件改编，2009年1月15日，萨利（汤姆·汉克斯 Tom Hanks 饰）在全美航空1549号班担任机长，飞机起飞两分钟后遭到飞鸟攻击，两架发动机全部熄火，萨利决定在哈德逊河上迫降，155人全数生还。但之后的调查显示他做了错误的抉择，认为大可选择返回拉瓜地亚机场。机内到底发生了什么呢？",
              "posterURL": "https://img3.doubanio.com/view/photo/l_ratio_poster/public/p2403319543.jpg",
              "posterURLKey": "x_tTSR35SDRTFhJqMWLk_.jpeg",
              "rawTitle": "Sully",
              "videoCoverURL": "https://img3.doubanio.com/img/trailer/medium/2401407510.jpg?",
              "videoCoverURLKey": "-IyG-QAuh7gNnfa6MHzqA.jpeg",
              "videoURL": "http://vt1.doubanio.com/201812222141/f3810ed6793c6eabc4de9d7e719f4f30/view/movie/M/302070937.mp4",
              "videoURLKey": "6FEi4IWYtvHERm3tw6RAB.mp4",
              "year": 2016
            }
          ]
        }
